### ISSUE TITLE
Basic UI Structure for all pages 

### ISSUE THREAD

**Issue by stephaniegiang** [stephaniegiang/Android-Mortgage-Calculator-App#2]
<img width="892" alt="image" src="https://user-images.githubusercontent.com/22784140/51791476-99640200-2171-11e9-9d79-d92100a3c4d4.png">

**Comment by Projudah** [comment]
![ui](https://user-images.githubusercontent.com/23324212/51791512-5eae9980-2172-11e9-927a-61650694089b.jpg)

**Comment by stephaniegiang** [comment]
Finished
